nato:
    build: .
    restart: always
    dockerfile: Dockerfile.nato
    environment:
        - ETCD_HOST=etcd
        - ETCD_PORT=4001
        # Set here the public IP (or hostname) of the host
        - EXTERNAL_IP=localhost
    links:
        - etcd:etcd
    volumes:
        - /ssh_hosts:/ssh_hosts
    volumes_from:
        - nginx

etcd:
    image: quay.io/coreos/etcd
    environment:
        - ETCD_NAME=natoetcd
        - ETCD_DATA_DIR=/data
        - ETCD_INITIAL_CLUSTER_STATE=new
        # Use in the following three variables the (private) IP of this host
        - ETCD_ADVERTISE_CLIENT_URLS=http://localhost:4001
        - ETCD_INITIAL_CLUSTER=natoetcd=http://localhost:4001
        - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://localhost:4001
        - ETCD_INITIAL_CLUSTER_TOKEN=8ea70dbac4494de1902d5e282e1db85f
        - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:7001
        - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:4001
    volumes:
        - /var/etcd:/data
    ports:
        - "4001:4001"
        - "7001:7001"

nginx:
    build: .
    dockerfile: Dockerfile.nginx
    ports:
        - "80:80"
        - "443:443"
